### ISSUE TITLE
Could not start application typex

### ISSUE THREAD

**Issue by marvinhagemeister** [blackode/printex#1]
I'm really new to Elixir, so forgive me if this is a beginner question.

I just followed the instructions to install `printex` by adding it to `mix.exs` and running `mix deps.get`

```exs
# mix.exs
defp deps do
  [{:printex, "~> 0.1"}]
end
```

...and put it in a simple function:

```ex
defmodule Foo do
  import Printex

  def foo() do
    Printex.prints("foo bar baz", :red, :cyan)
  end
end
```

But whenever I run the code I get the following error:

```bash
** (Mix) Could not start application typex: could not find application file: typex.app
```

**Comment by blackode** [comment]
Hi @marvinhagemeister 

There is nothing wrong with your approach. This library is depending on `typex` a module that helps to find the data type.       

There was a plan to print the data types in color format based on the `type` of data. We removed that. And we haven't published to `hex` yet. Just install the library from `git` as in following way...


```elixir
# mix.exs
  defp deps do
    [ {:printex, git: "https://github.com/blackode/printex.git"}]
  end

```
I hope this will solve the problem.           



Thank you for the participation.

**Happy Coding !!**

**Comment by marvinhagemeister** [comment]
@blackode Awesome, that works 🎉  Wasn't aware that mix supports pulling straight from git repos. That's good to know. Thanks for your kind response, and an awesome package 👍
